[package]
name = "tappy"
version = "0.1.0"
authors = ["Justinas Stankevicius <justinas@justinas.org>"]

[dependencies.cursive]
version = "0.9.2"
default-features = false
features = ["termion-backend"]
